// flow-typed signature: 85ebdd300dd5dfcdada96de7cfdf49e2
// flow-typed version: <<STUB>>/json-concat_v^0.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-concat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-concat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-concat/lib/cli' {
  declare module.exports: any;
}

declare module 'json-concat/lib/cmd' {
  declare module.exports: any;
}

declare module 'json-concat/lib/json-concat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-concat/lib/cli.js' {
  declare module.exports: $Exports<'json-concat/lib/cli'>;
}
declare module 'json-concat/lib/cmd.js' {
  declare module.exports: $Exports<'json-concat/lib/cmd'>;
}
declare module 'json-concat/lib/json-concat.js' {
  declare module.exports: $Exports<'json-concat/lib/json-concat'>;
}
