// flow-typed signature: 6f4ac46034a55b4d5d37c037a6ca2cc0
// flow-typed version: <<STUB>>/phoenixjs_v^1.0.5/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phoenixjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'phoenixjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'phoenixjs/phoenix' {
  declare module.exports: any;
}

// Filename aliases
declare module 'phoenixjs/phoenix.js' {
  declare module.exports: $Exports<'phoenixjs/phoenix'>;
}
