// flow-typed signature: 9403a77fb14b20979d3704b6aa9168bf
// flow-typed version: <<STUB>>/postcss-font-magician_v^1.4.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-font-magician'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-font-magician' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-font-magician/loader' {
  declare module.exports: any;
}

declare module 'postcss-font-magician/loader.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-font-magician/index' {
  declare module.exports: $Exports<'postcss-font-magician'>;
}
declare module 'postcss-font-magician/index.js' {
  declare module.exports: $Exports<'postcss-font-magician'>;
}
declare module 'postcss-font-magician/loader.js' {
  declare module.exports: $Exports<'postcss-font-magician/loader'>;
}
declare module 'postcss-font-magician/loader.min.js' {
  declare module.exports: $Exports<'postcss-font-magician/loader.min'>;
}
