// flow-typed signature: 3d2cf472c3112a89f5b6b0bddddef259
// flow-typed version: <<STUB>>/socketcluster-client_v^5.2.5/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socketcluster-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'socketcluster-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'socketcluster-client/lib/auth' {
  declare module.exports: any;
}

declare module 'socketcluster-client/lib/response' {
  declare module.exports: any;
}

declare module 'socketcluster-client/lib/scsocket' {
  declare module.exports: any;
}

declare module 'socketcluster-client/lib/scsocketcreator' {
  declare module.exports: any;
}

declare module 'socketcluster-client/lib/sctransport' {
  declare module.exports: any;
}

declare module 'socketcluster-client/lib/ws-browser' {
  declare module.exports: any;
}

declare module 'socketcluster-client/socketcluster' {
  declare module.exports: any;
}

declare module 'socketcluster-client/socketcluster.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'socketcluster-client/index' {
  declare module.exports: $Exports<'socketcluster-client'>;
}
declare module 'socketcluster-client/index.js' {
  declare module.exports: $Exports<'socketcluster-client'>;
}
declare module 'socketcluster-client/lib/auth.js' {
  declare module.exports: $Exports<'socketcluster-client/lib/auth'>;
}
declare module 'socketcluster-client/lib/response.js' {
  declare module.exports: $Exports<'socketcluster-client/lib/response'>;
}
declare module 'socketcluster-client/lib/scsocket.js' {
  declare module.exports: $Exports<'socketcluster-client/lib/scsocket'>;
}
declare module 'socketcluster-client/lib/scsocketcreator.js' {
  declare module.exports: $Exports<'socketcluster-client/lib/scsocketcreator'>;
}
declare module 'socketcluster-client/lib/sctransport.js' {
  declare module.exports: $Exports<'socketcluster-client/lib/sctransport'>;
}
declare module 'socketcluster-client/lib/ws-browser.js' {
  declare module.exports: $Exports<'socketcluster-client/lib/ws-browser'>;
}
declare module 'socketcluster-client/socketcluster.js' {
  declare module.exports: $Exports<'socketcluster-client/socketcluster'>;
}
declare module 'socketcluster-client/socketcluster.min.js' {
  declare module.exports: $Exports<'socketcluster-client/socketcluster.min'>;
}
