// flow-typed signature: d372c6fad451cd0e6ca2c5ae116decce
// flow-typed version: <<STUB>>/storybook-addon-specifications_v^1.0.15/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-specifications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-specifications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-specifications/dist/components/Specifications/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/dist/components/Specifications/style' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/dist/containers/Specifications/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/dist/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/dist/manager' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/dist/preview' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/register' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/src/components/Specifications/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/src/components/Specifications/style' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/src/containers/Specifications/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/src/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/src/manager' {
  declare module.exports: any;
}

declare module 'storybook-addon-specifications/src/preview' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-specifications/dist/components/Specifications/index.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/components/Specifications/index'>;
}
declare module 'storybook-addon-specifications/dist/components/Specifications/style.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/components/Specifications/style'>;
}
declare module 'storybook-addon-specifications/dist/containers/Specifications/index.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/containers/Specifications/index'>;
}
declare module 'storybook-addon-specifications/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/index'>;
}
declare module 'storybook-addon-specifications/dist/manager.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/manager'>;
}
declare module 'storybook-addon-specifications/dist/preview.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/dist/preview'>;
}
declare module 'storybook-addon-specifications/register.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/register'>;
}
declare module 'storybook-addon-specifications/src/components/Specifications/index.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/src/components/Specifications/index'>;
}
declare module 'storybook-addon-specifications/src/components/Specifications/style.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/src/components/Specifications/style'>;
}
declare module 'storybook-addon-specifications/src/containers/Specifications/index.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/src/containers/Specifications/index'>;
}
declare module 'storybook-addon-specifications/src/index.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/src/index'>;
}
declare module 'storybook-addon-specifications/src/manager.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/src/manager'>;
}
declare module 'storybook-addon-specifications/src/preview.js' {
  declare module.exports: $Exports<'storybook-addon-specifications/src/preview'>;
}
