// flow-typed signature: 2ad714225ca1ffd6ed9bf37a357c0390
// flow-typed version: <<STUB>>/stylelint-order_v^0.3.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-order'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-order' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-order/rules/declaration-block-order/index' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/declaration-block-properties-alphabetical-order/index' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/declaration-block-properties-specified-order/index' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/declaration-block-property-groups-structure/index' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/index' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/checkAlpabeticalOrder' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/index' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/isAtVariable' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/isCustomProperty' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/isDollarVariable' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/isStandardSyntaxProperty' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/namespace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-order/index' {
  declare module.exports: $Exports<'stylelint-order'>;
}
declare module 'stylelint-order/index.js' {
  declare module.exports: $Exports<'stylelint-order'>;
}
declare module 'stylelint-order/rules/declaration-block-order/index.js' {
  declare module.exports: $Exports<'stylelint-order/rules/declaration-block-order/index'>;
}
declare module 'stylelint-order/rules/declaration-block-properties-alphabetical-order/index.js' {
  declare module.exports: $Exports<'stylelint-order/rules/declaration-block-properties-alphabetical-order/index'>;
}
declare module 'stylelint-order/rules/declaration-block-properties-specified-order/index.js' {
  declare module.exports: $Exports<'stylelint-order/rules/declaration-block-properties-specified-order/index'>;
}
declare module 'stylelint-order/rules/declaration-block-property-groups-structure/index.js' {
  declare module.exports: $Exports<'stylelint-order/rules/declaration-block-property-groups-structure/index'>;
}
declare module 'stylelint-order/rules/index.js' {
  declare module.exports: $Exports<'stylelint-order/rules/index'>;
}
declare module 'stylelint-order/utils/checkAlpabeticalOrder.js' {
  declare module.exports: $Exports<'stylelint-order/utils/checkAlpabeticalOrder'>;
}
declare module 'stylelint-order/utils/index.js' {
  declare module.exports: $Exports<'stylelint-order/utils/index'>;
}
declare module 'stylelint-order/utils/isAtVariable.js' {
  declare module.exports: $Exports<'stylelint-order/utils/isAtVariable'>;
}
declare module 'stylelint-order/utils/isCustomProperty.js' {
  declare module.exports: $Exports<'stylelint-order/utils/isCustomProperty'>;
}
declare module 'stylelint-order/utils/isDollarVariable.js' {
  declare module.exports: $Exports<'stylelint-order/utils/isDollarVariable'>;
}
declare module 'stylelint-order/utils/isStandardSyntaxProperty.js' {
  declare module.exports: $Exports<'stylelint-order/utils/isStandardSyntaxProperty'>;
}
declare module 'stylelint-order/utils/namespace.js' {
  declare module.exports: $Exports<'stylelint-order/utils/namespace'>;
}
