// flow-typed signature: 10808ca587806e4ea3e9a1b2280d4d60
// flow-typed version: <<STUB>>/sugarss_v^0.2.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sugarss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sugarss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sugarss/liner' {
  declare module.exports: any;
}

declare module 'sugarss/parse' {
  declare module.exports: any;
}

declare module 'sugarss/parser' {
  declare module.exports: any;
}

declare module 'sugarss/preprocess' {
  declare module.exports: any;
}

declare module 'sugarss/stringifier' {
  declare module.exports: any;
}

declare module 'sugarss/stringify' {
  declare module.exports: any;
}

declare module 'sugarss/tokenize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sugarss/index' {
  declare module.exports: $Exports<'sugarss'>;
}
declare module 'sugarss/index.js' {
  declare module.exports: $Exports<'sugarss'>;
}
declare module 'sugarss/liner.js' {
  declare module.exports: $Exports<'sugarss/liner'>;
}
declare module 'sugarss/parse.js' {
  declare module.exports: $Exports<'sugarss/parse'>;
}
declare module 'sugarss/parser.js' {
  declare module.exports: $Exports<'sugarss/parser'>;
}
declare module 'sugarss/preprocess.js' {
  declare module.exports: $Exports<'sugarss/preprocess'>;
}
declare module 'sugarss/stringifier.js' {
  declare module.exports: $Exports<'sugarss/stringifier'>;
}
declare module 'sugarss/stringify.js' {
  declare module.exports: $Exports<'sugarss/stringify'>;
}
declare module 'sugarss/tokenize.js' {
  declare module.exports: $Exports<'sugarss/tokenize'>;
}
