// flow-typed signature: ae2591bbbf036115d58fcf50ff7b67ce
// flow-typed version: <<STUB>>/@kadira/storybook-addon-notes_v^1.0.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/storybook-addon-notes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/storybook-addon-notes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/storybook-addon-notes/dist/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-notes/dist/register' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-notes/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/storybook-addon-notes/dist/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-notes/dist/index'>;
}
declare module '@kadira/storybook-addon-notes/dist/register.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-notes/dist/register'>;
}
declare module '@kadira/storybook-addon-notes/register.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-notes/register'>;
}
